services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./app:/app/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - ws-network

networks:
  ws-network:
    name: ws-network
    driver: bridge
    external: true
